apiVersion: networking.k8s.io/v1
kind: ingress
metadata:
  name: journey-builder-application
spec:
  tls:
    - secretName: jbc-tls
  defaultBackend:
    service:
      name: journey-builder
      port:
        number: 80
---