apiVersion: networking.k8s.io/v1
kind: ingress
metadata:
  name: basic-ingress
spec:
  tls:
    - secretName: jbc-tls
  defaultBackend:
    service:
      name: web
      port:
        number: 3000
---